version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - codecalm
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: fullcalendar
    versions:
    - 5.5.0
    - 5.5.1
  - dependency-name: "@fullcalendar/daygrid"
    versions:
    - 5.5.0
  - dependency-name: rollup-plugin-filesize
    versions:
    - 9.1.0
  - dependency-name: percy
    versions:
    - 0.28.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
